# version: '2'

front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mariadb:mysql
    - mongo:mongo
    - memcached:memcached
    - redis:redis
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor


mariadb:
  image: mariadb
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes:
    - ./storage/mysql:/var/lib/mysql

mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - ./conf/mongod.conf:/etc/mongod.conf
    - ./storage/mongodb:/data/db
  command: --config /etc/mongod.conf

memcached:
  image: memcached
  ports:
    - "11121:11121"

redis:
  image: redis
  ports:
    - "6379:6379"
